name: Hourly update
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  debian-mirrors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install requests beautifulsoup4
    - name: Pull latest changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin main
    - name: Run fetcher script and generate EDL
      run: python debian-mirrors/debian-mirrors.py
    - name: Commit and push if changes
      run: |
        git add debian-mirrors/debian-mirrors.txt
        git commit -m "Update Debian Mirror list" -a || echo "No changes to commit"
        git push origin main || echo "Push failed, retrying..." && git pull --rebase origin main && git push origin main

  ubuntu-mirrors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install requests beautifulsoup4
    - name: Pull latest changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin main
    - name: Run fetcher script and generate EDL
      run: python ubuntu-mirrors/ubuntu-mirrors.py
    - name: Commit and push if changes
      run: |
        git add ubuntu-mirrors/ubuntu-mirrors.txt
        git commit -m "Update Ubuntu Mirror list" -a || echo "No changes to commit"
        git push origin main || echo "Push failed, retrying..." && git pull --rebase origin main && git push origin main
